import type {Compiler, WebpackPluginInstance} from "webpack";
import glob from "fast-glob";
import fs from "fs";

export class ImageRecordPlugin implements WebpackPluginInstance {
    private imagePath: string;
    private outputPath: string;

    constructor(imagePath: string, outputPath: string)
    {
        this.imagePath = imagePath;
        this.outputPath = outputPath;
    }

    public apply(compiler: Compiler){
        compiler.hooks.beforeCompile.tap("ImageRecordPlugin", () =>
        {
            const imageFiles = glob.sync(`${this.imagePath}/**/*.{png,jpg,jpeg,gif,svg}`, {
                cwd: process.cwd(),
            });

            const comments = [`// This file is auto-generated by ImageRecordPlugin. manual edits will be lost\n`];
            const importLines: string[] = [];
            const recordItemLines: string[] = [];

            for (const file of imageFiles)
            {
                const fileName = file.split("/").pop()?.split(".")[0] as string;
                importLines.push(`import ${fileName} from "../../${file}";`);
                recordItemLines.push(`${fileName}: ${fileName} as string`);
            }

            const tsContents = comments.join("\n") + importLines.join("\n") + "\n\nexport const GeneratedImageRecord = {\n" + recordItemLines.join(",\n") + "\n} as const;\n\nexport default GeneratedImageRecord;\n";

            fs.mkdirSync(this.outputPath, { recursive: true });

            const tsPath = `${this.outputPath}/GeneratedImageRecord.ts`;
            if (fs.existsSync(tsPath)) {
                const existing = fs.readFileSync(tsPath, "utf8");
                if (existing !== tsContents)
                {
                    fs.writeFileSync(tsPath, tsContents);
                }
            }
        });
    }
}