import DissertationPosterImage from "../../public/image-components/DissertationPoster.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const DissertationPoster = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={DissertationPosterImage} {...props}/>
    )
}