import FreightScreenshotImage from "../../public/image-components/FreightScreenshot.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const FreightScreenshot = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={FreightScreenshotImage} {...props}/>
    )
}