import GithibLogoImage from "../../public/image-components/GithibLogo.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const GithibLogo = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={GithibLogoImage} {...props}/>
    )
}