import InspirationalStudentOfTheYearImage from "../../public/image-components/InspirationalStudentOfTheYear.jpeg";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const InspirationalStudentOfTheYear = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={InspirationalStudentOfTheYearImage} {...props}/>
    )
}