import ItchIoLogoImage from "../../public/image-components/ItchIoLogo.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const ItchIoLogo = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={ItchIoLogoImage} {...props}/>
    )
}