import JamesPortraitImage from "../../public/image-components/JamesPortrait.jpg";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const JamesPortrait = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={JamesPortraitImage} {...props}/>
    )
}