import JamesPresentationImage from "../../public/image-components/JamesPresentation.jpg";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const JamesPresentation = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={JamesPresentationImage} {...props}/>
    )
}