import KnightlyKnockoutScreenshotImage from "../../public/image-components/KnightlyKnockoutScreenshot.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const KnightlyKnockoutScreenshot = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={KnightlyKnockoutScreenshotImage} {...props}/>
    )
}