import LinkedinLogoImage from "../../public/image-components/LinkedinLogo.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const LinkedinLogo = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={LinkedinLogoImage} {...props}/>
    )
}