import MailIconImage from "../../public/image-components/MailIcon.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const MailIcon = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={MailIconImage} {...props}/>
    )
}