import SkyImageImage from "../../public/images/SkyImage.jpg";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const SkyImage = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={SkyImageImage} {...props}/>
    )
}