import TigaGradOfTheYearImage from "../../public/image-components/TigaGradOfTheYear.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const TigaGradOfTheYear = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={TigaGradOfTheYearImage} {...props}/>
    )
}