import UnityHonourableMentionImage from "../../public/image-components/UnityHonourableMention.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const UnityHonourableMention = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={UnityHonourableMentionImage} {...props}/>
    )
}