import YoutubeLogoImage from "../../public/images/YoutubeLogo.png";
import {ImgHTMLAttributes} from "react";

// This file is auto-generated by ImageRecordPlugin. manual edits will be lost
export const YoutubeLogo = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={YoutubeLogoImage} {...props}/>
    )
}